<?php

class FindTest extends \PHPUnit\Framework\TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testPrecessTweetsThatNeedResponses()
    {
        $response = json_decode(file_get_contents(__DIR__ . '/../example-responses/mentions-in-reply.json'));
        $tweetData = reset($response->data);
        $createdAt = new DateTime();
        $createdAt->setTimestamp((int) $tweetData->created_at);
        $tweetToRepondTo = new \Balsama\Bostonplatebot\BiElTweet(
            $tweetData->author_id,
            $tweetData->conversation_id,
            $createdAt,
            $tweetData->id,
            $tweetData->text,
        );

        $finder = new \Balsama\Bostonplatebot\Find('lan');

        $finder->processTweetThatNeedsRespons($tweetToRepondTo);
    }
}